name: news_app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"
dependencies:
  animated_splash_screen: ^1.2.0
  cached_network_image: ^3.2.0
  cloud_firestore: ^3.1.14
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.3.17
  firebase_core: ^1.16.0
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.1.0
  fluttertoast: ^8.0.9
  json_annotation: ^4.5.0
  logger: ^1.1.0
  url_launcher: ^6.1.2

dev_dependencies:
  build_runner: ^2.1.10
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  icons_launcher: ^1.1.7
  json_serializable: ^6.2.0
flutter_icons:
  image_path: "assets/logo.png"
  ios: true
  android: true
flutter:
  uses-material-design: true
  assets:
    - assets/
